table Sales
	lineageTag: 00000003-0000-0000-0000-000000000003

	column ProductKey
		dataType: string
		lineageTag: 00000004-0000-0000-0000-000000000004
		sourceColumn: ProductKey

	column Amount
		dataType: decimal
		lineageTag: 00000005-0000-0000-0000-000000000005
		sourceColumn: Amount

	measure 'Total Amount' = SUM(Sales[Amount])
		formatString: $ #,0.00;($ #,0.00);$ #,0.00
		lineageTag: 00000006-0000-0000-0000-000000000006

	partition Sales-Sales
		mode: import
		source
			type: m
			expression
				let
					Source = Table.FromRows({})
				in
					Source

	annotation PBI_ResultType = Table
